Repository 9oormthon-univ/2024_DANPOONG_TEAM_15_FE, pull requests merged in 2024-12, with the labels that each got.

#45 🔨 Fix Calendar & Time picker bug
  src/components/.gitkeep
  src/components/request/Calendar.tsx
  src/components/request/TimePicker.tsx
  src/components/request/WarnCard.tsx
  src/routes/AbsentConfirm.tsx
  src/routes/AbsentList.tsx
  src/routes/Schedule.tsx
  src/routes/Time.tsx
  src/styles/ScheduleStyle.ts
  src/styles/TimeStyle.ts
  src/styles/components/CalendarStyle.ts
  src/styles/components/WarnCardStyle.ts
  yarn.lock
Labels: 🐞 BugFix, 🔨 Refactor

#47 ✨ Apply LottieFiles to Main and Loading
  package.json
  src/components/request/RequestLoading.tsx
  src/lib/colorPalette.ts
  src/routes/Main.tsx
  src/styles/MainStyle.ts
  src/styles/components/RequestLoadingStyle.ts
  vite.config.ts
  yarn.lock
Labels: ✨ Feature, 🎨 Html&Css

#49 ✨ Apply memo page UI, API and modify time flow
  src/App.tsx
  src/const/color.ts
  src/routes/Memo.tsx
  src/routes/Time.tsx
  src/styles/MemoStyle.ts
  src/utils/requestApi.tsx
Labels: ✨ Feature, 📬 API, 🎨 Html&Css

#51 ✨ Create alarm page UI & modify header
  src/App.tsx
  src/assets/icons/alarm/circle-link.svg
  src/assets/icons/common/alarm-bell.svg
  src/assets/icons/common/alarm-orange.svg
  src/assets/icons/common/alarm-red.svg
  src/assets/icons/common/ivory-logo.svg
  src/assets/icons/common/mypage.svg
  src/assets/icons/request/circle-close.svg
  src/components/Header.tsx
  src/components/alarm/AlarmCard.tsx
  src/components/alarm/AlarmToast.tsx
  src/components/alarm/MainAlarmToast.tsx
  src/const/color.ts
  src/routes/Absent.tsx
  src/routes/AbsentConfirm.tsx
  src/routes/Certificate.tsx
  src/routes/CertificateConfirm.tsx
  src/routes/Main.tsx
  src/routes/Notifications.tsx
  src/styles/AbsentConfirmStyle.ts
  src/styles/AbsentStyle.ts
  src/styles/CertificateConfirmStyle.ts
  src/styles/CertificateStyle.ts
  src/styles/NotificationsStyle.ts
  src/styles/components/AlarmCardStyle.ts
  src/styles/components/AlarmToastStyle.ts
  src/styles/components/HeaderStyle.ts
  src/styles/components/MainAlarmToastStyle.ts
Labels: ✨ Feature, 🎨 Html&Css

#53 ✨ Create caregivers pages UI & API
  src/App.tsx
  src/assets/brown-arrow-right.svg
  src/assets/gray-arrow-right.svg
  src/assets/icons/common/gray-bory.svg
  src/components/CareHeader.tsx
  src/components/caregiver/GrayCareButton.tsx
  src/components/caregiver/SelectCareCard.tsx
  src/components/common/TopXBar.tsx
  src/components/main/CareCard.tsx
  src/components/main/NonCareCard.tsx
  src/components/main/RequestCareButton.tsx
  src/const/color.ts
  src/routes/CaregiverRoute.tsx
  src/routes/Login.tsx
  src/routes/PrivateRoute.tsx
  src/routes/caregiver/CaregiverDetail.tsx
  src/routes/caregiver/CaregiverDone.tsx
  src/routes/caregiver/CaregiverInform.tsx
  src/routes/caregiver/CaregiverList.tsx
  src/routes/caregiver/CaregiverMain.tsx
  src/styles/caregiver/CaregiverDetailStyle.ts
  src/styles/caregiver/CaregiverDoneStyle.ts
  src/styles/caregiver/CaregiverListStyle.ts
  src/styles/caregiver/CaregiverMainStyle.ts
  src/styles/caregiver/SelectCareCardStyle.ts
  src/styles/components/CareCardStyle.ts
  src/styles/components/HeaderStyle.ts
  src/styles/components/RequestButtonStyle.ts
  src/types/schema.ts
  src/utils/caregiverApi.tsx
  src/utils/config/config.tsx
  src/utils/userApi.tsx
Labels: ✨ Feature, 📬 API, 🎨 Html&Css

#55 ✨ Create UI for Custom 404
  src/assets/icons/common/custom-404.svg
  src/routes/Non.tsx
  src/styles/NonStyle.ts
Labels: ✨ Feature, 🎨 Html&Css

#57 ✨ Implement socket connection feature
  src/routes/Main.tsx
  src/utils/useWebSocket.ts
  yarn.lock
Labels: ✨ Feature, 📬 API
